### ISSUE TITLE
Song and Story Ability

### ISSUE THREAD

**Issue by jwmuk** [chrisesharp/foundryvtt-dee-sanction#12]
The **Song and Story** ability is not showing up in the tickbox for the Minstrel occupation, might be because it is called **Songs and Stories** as an ability or **Songs and Story** in the Occupation?

![image](https://user-images.githubusercontent.com/244573/125167331-e00a1300-e197-11eb-9818-7e9a92b3bd26.png)

**Comment by chrisesharp** [comment]
Argh! I thought I'd caught all these. Turns out neither was correct! Now the Minstrel references the Ability "Song and Story" correctly.

I've fixed this in 1.1.0, but for purposes of updating, I would suggest you do the following, in this order:

1. update the system to v1.1.0
2. delete the  occupation "Minstrel" and ability "Songs and Stories",
3. manually import the ability "Song and Story" from the compendium,
4. manually import the occupation "Minstrel" from the compendium

Given you've got a lot of content in your world, I think that would be safer than deleting all the imported content and starting again.
