### ISSUE TITLE
New Occupation creates immoveable text

### ISSUE THREAD

**Issue by jwmuk** [chrisesharp/foundryvtt-dee-sanction#14]
Steps to recreate:

1. Create a new character
2. Create a new item (occupation)
3. Drag and drop onto new character
4. Delete occupation from character sheet

![image](https://user-images.githubusercontent.com/244573/130368138-6a1e75e4-0afb-4ea4-895d-4f5180a48dea.png)

NB - I didn't realise this space was for the occupation, doesn't seem to work for existing occupations

**Comment by chrisesharp** [comment]
Hmm..that's odd...it seems to work perfectly for the existing occupations as well as the new ones, for me. 

It is set by the "most recent" occupation to be dropped onto the sheet. So, if you drag another occupation on, it will replace the text with that. Since a character MUST have an occupation, it didn't seem necessary to clear it, as just dragging a new occupation fixes it.

Are you working with a clean, properly installed set up where the system imported all the latest content from scratch?

**Comment by jwmuk** [comment]
I have a nodejs install of foundry let me upgrade to 0.8.9 then do a clean install of dee sanction 1.1.0, will feedback.  What are the steps for a clean, proper install? Uninstall then install, do I need to clear anything out from the system dir?

**Comment by chrisesharp** [comment]
You should be able to just upgrade the system to 1.1.0, but create a new world...that should be all you need to do.

**Comment by chrisesharp** [comment]
otherwise, you'll need to delete all the standard provided items and folders, and then go into settings to re-enable the check to import at startup. This will then import everything again cleanly....but it's much safer to start with a new world ;-)

**Comment by jwmuk** [comment]
All works fine on foundry 0.8.7 when I set up a new world, also tried this with nodejs on version 0.8.9, all good.
