### ISSUE TITLE
Inclusion of "The Sight"

### ISSUE THREAD

**Issue by newbyr** [chrisesharp/foundryvtt-dee-sanction#16]
Hi Chris.  great work on this, the reason I migrated from Roll20 to FoundryVVT (!).

Have you any plans to include the extra elements from "The Sight"  ?

Thanks
Richard N

**Comment by chrisesharp** [comment]
Hi Richard...wow, thanks, that's great to hear :-)

As yet, I haven't been planning to, because I prefer my games low-magic. However, I recently read Pookie's review and it's changing my mind. I know @jwmuk would be keen on it, too!

I'm not sure what's involved yet, but I will take a look and see. I was hoping there wasn't anything too significant, and that it was more a question of just content on the system, rather than underlying changes?

**Comment by newbyr** [comment]
Hi Chris

The major point of The Sight is to give a character the chance (1/12) to
get a low form of magick.  It's mainly a new "Favours" table to D8+d12
instead of D4+d10. Plus the relevant compendium changes.

The reason I ask is that the adventures in the "Adventures" pack from All
Rolled Up (sold separately  on Drivethru) refer to some of the talents in
the Sight.

You've done an excellent job with the pack.  I'm not a coder at heart, but
if you need some assistance with gruntwork of typing info into paragraphs,
rhen give me a call.

Thanks.

Richard

**Comment by chrisesharp** [comment]
Thanks Richard - I'll take a look and see what needs doing.

**Comment by chrisesharp** [comment]
OK...having read through The Sight now, I think the only real change needed is to add the set of "Sights" in as new items from their own compendium, and change the random generation of a Favour to pick a Sight if an 11 or 12 is rolled internally. I've made these changes in `1.3.0` now, so you should be able to take a look.

I've modelled the Sights as favours in the system but just add a title in their description to indicate which of the four areas of The Sight they fall under.

Hopefully this should capture what's needed.

N.B. you will probably need to go into Settings-System and untick the `Initialized` checkbox so the new compendium is imported.

**Comment by chrisesharp** [comment]
@iwmuk - you might want to take a look at this too?

**Comment by chrisesharp** [comment]
OK - updated to 1.3.1 because the git tags hadn't been set and Foundry wasn't making it "look" like it was the correct version, even though it was :-/

**Comment by jwmuk** [comment]
Hi, I tested this successfully.  

I backed up.  I then updated to 1.3.1 and then unticked the Initialized checkbox as you said and then exited and went in again, then clicked on Import.

After creating a new character, I then tried to create a series of esoterica and caught a couple of The Sight favours/gifts.

Given these values in the attached, looks like you have implemented the following rule "_If you use dice to create an Agent, use a d8 and a d12 instead of a d4 and a d10 on the Favours table. The smaller die denotes the column, like the d4, but if the d12 generates a 12, an odd on the d8 equates to a Queen result, even a King result._"

NB - I'll raise a separate issue/option for implementation, but I think it does what it needs to to be able to create The Sight Characters, thanks!

![image](https://user-images.githubusercontent.com/244573/170511969-01bc494a-01e5-4fd0-bb5d-bdfd2c558984.png)

**Comment by chrisesharp** [comment]
Thanks Jim

**Comment by newbyr** [comment]
Thanks Chris
This is super quick.

I'll have a look later today.

Richard

**Comment by chrisesharp** [comment]
All done now in 1.3.2.
