### ISSUE TITLE
The Sight Suggestions

### ISSUE THREAD

**Issue by jwmuk** [chrisesharp/foundryvtt-dee-sanction#17]
@newbyr

1. **The Sight Optional** - I can think of two ways but I'll leave it up to you if you feel it's worth the effort  - 1. system configuration to tick The Sight off /on for random selection of favours 2. tickbox on the character sheet to do the same
2. **O Fickle Fortune** - Create a rollable table or macro for the outcome of a vision, dream, omen or reading i.e. the two tables on pp10-11
 - e.g. roll d4 and d10 on **Table 1 Outcomes** and getting 2 and 7 = Honesty/Deception, then take a chance 2 = Deception, then roll d4 and d6 on **Table 2 Subject** and getting 1 and 2 = The Divinant therefore "_The outcome is deception for the divinant_"

**Comment by chrisesharp** [comment]
OK.. @jwmuk and @newbyr

1. I've added a Setting to enable The Sight (the rules say you should agree as a table, so it needs to be all or nothing)
2. I've added a Macro called `O Fickle Fortune` and associated RollTables to support it. I haven't built a fancy combo, I'm afraid - it just rolls separately on each table in sequence...but it's there, at least.
3. I've updated the documentation to reflect all this.

If you update to 1.3.2 you'll get these. I would recommend deleting your `Outcomes` folder and your `Macros` folder, and re-initializing the system to import in the new macros and rolltables.

**Comment by newbyr** [comment]
Many thanks Chris   From: Chris SharpSent: 30 May 2022 17:57To: chrisesharp/foundryvtt-dee-sanctionCc: newbyr; MentionSubject: Re: [chrisesharp/foundryvtt-dee-sanction] The Sight Suggestions (Issue #17) OK.. @jwmuk and @newbyrI've added a Setting to enable The Sight (the rules say you should agree as a table, so it needs to be all or nothing)I've added a Macro called O Fickle Fortune and associated RollTables to support it. I haven't built a fancy combo, I'm afraid - it just rolls separately on each table in sequence...but it's there, at least.I've updated the documentation to reflect all this.If you update to 1.3.2 you'll get these. I would recommend deleting your Outcomes folder and your Macros folder, and re-initializing the system to import in the new macros and rolltables.—Reply to this email directly, view it on GitHub, or unsubscribeYou are receiving this because you were mentioned.Message ID: ***@***.***> 



	
		
			
				
			
		
		
			
				This email has been checked for viruses by Avast antivirus software.
				www.avast.com
