### ISSUE TITLE
Attempting to add Consequence fails

### ISSUE THREAD

**Issue by steveculshaw** [chrisesharp/foundryvtt-dee-sanction#21]
Trying to add a consequence to a character

Click on the "New Consquence" ...

> can't edit it
> get a "DEE.resource..long 1" ... see attached screenshot

![Screenshot 2022-07-27 151104](https://user-images.githubusercontent.com/64320/181272408-38d7cbe2-4544-47de-8d60-4098392e48ae.png)

**Comment by chrisesharp** [comment]
Thanks @steveculshaw ...I'm amazed this hasn't been spotted before! The problem is the `+` sign to add a Consequence should never have been there in the first place. You can only drag consequences from the sidebar or the chat window, not create them in-situ in the character sheet.

I'll remove that and spin a new version but in the meantime, just create consequences as items, and drag them onto sheets.

**Comment by steveculshaw** [comment]
Ah ha !!!

Ta
