### ISSUE TITLE
Issue with Dee Sanction on Forge

### ISSUE THREAD

**Issue by nclarke1982** [chrisesharp/foundryvtt-dee-sanction#25]
having done an update of FVTT for v10 I find that the right hand side bar has disappeared for my Dee Sanction game setup.
Checking I find it does not appear to be an issue on a local install just on the forge. A refresh doesn't bring it back either. 
![image](https://user-images.githubusercontent.com/71648468/216039249-d07d17ae-6760-4a59-8a28-a6b93bdbdd5a.png)
![image](https://user-images.githubusercontent.com/71648468/216039309-02c288d8-f479-47e7-b7c7-24eed6ed9857.png)

**Comment by chrisesharp** [comment]
Hi @nclarke1982 I tried running the system with both libwrapper and combat carousel modules enabled, and I only saw that second DevTools message, which appears to be a problem with that module...but it didn't recreate your problem.

Since the red error is being thrown by libwrapper, and it only seems to be throwing it in Forge, I'm not able to figure out what is actually causing the problem, and whether it's anything to do with the Dee system or another module.

Are you able to disable all other modules and turn them on one by one?

**Comment by chrisesharp** [comment]
I just signed up for a Forge free-trial, created a Dee system world, enabled Combat Carousel and libWrapper....and again I don't see the problem you reported.
<img width="1790" alt="Screenshot 2023-02-01 at 17 03 34" src="https://user-images.githubusercontent.com/13590524/216111472-664b5dc3-806b-4cea-beda-5bebac53831e.png">

I'm afraid it looks like it is some other module.

**Comment by nclarke1982** [comment]
Because the menu is hidden/disappeared I can't switch anything off. That's
the problem I can't do any troubleshooting like turning off modiles. I'l
try Safe Mode with no modules and see if that works.

**Comment by nclarke1982** [comment]
OK switched to Safe Mode and it loaded fine. I added back all the mods
except Combat Carousel and it still works so I don't know what the issue
was. Thanks for taking a look at the issue.

**Comment by chrisesharp** [comment]
No worries....looking at another system of mine, Helvéczia, on the Forge I notice they do strange things with their own module that you cannot switch off (like intercept and screw around with asset links to make you use their own asset library) which causes V10 compatibility errors of their own, so I wouldn't be surprised if they have other strange bugs.
