### ISSUE TITLE
Missing Weapon

### ISSUE THREAD

**Issue by jwmuk** [chrisesharp/foundryvtt-dee-sanction#5]
Can you add Knife, the default weapon to the weapon list?

![image](https://user-images.githubusercontent.com/244573/123539874-c39bbe80-d733-11eb-85b7-712e5bd26e15.png)

**Comment by chrisesharp** [comment]
Ah....good question. 

So, I originally had a knife, but then made a conscious decision to leave knife out because:
1.  The folder of 10 weapons mirrors the rules, and can then be used as a rolltable the same as the rules, and
2.  The rules declare that everyone carries a knife...therefore, it's a given that you have one and not needed as an item

I think the assumption is that it's as common as the clothes you are wearing, so not needed as something particular to call out.

**Comment by jwmuk** [comment]
Yes, makes sense, easy to add a knife, but seems more thematic than something that impacts mechanics.
