### ISSUE TITLE
Random Name Lock/Unlock

### ISSUE THREAD

**Issue by jwmuk** [chrisesharp/foundryvtt-dee-sanction#8]
Proposal to lock the random name generator (dice icon) if the name field is populated.
This will be the default, as the name is mandatory when creating a new agent.
A blank Name field will unlock the button, right-clicking can also unlock the button.

**Comment by chrisesharp** [comment]
I was thinking of combining #9 with this issue, and also disabling the step up/down icons on resources, under a single sheet lock. i.e. start with everything editable/random-rollable with the icons visible, but then locking it hides the icons.

I've discovered that Foundry really doesn't like you clearing the name field (it throws an exception in the console, which seems a bit harsh) because it's a key value that needs to always be populated.

**Comment by chrisesharp** [comment]
Here's what it looks like...
<img width="478" alt="Screenshot 2021-07-04 at 13 44 32" src="https://user-images.githubusercontent.com/13590524/124385557-1c3c0000-dcce-11eb-99c0-873596d8160f.png">
<img width="478" alt="Screenshot 2021-07-04 at 13 44 38" src="https://user-images.githubusercontent.com/13590524/124385559-20681d80-dcce-11eb-8fcc-5fd5dd5761b4.png">

**Comment by jwmuk** [comment]
Works for me, feels similar to the Call of Cthulhu sheet that you can switch between read-only and edit mode.  How would it work for dragging and dropping items into it e.g. consequences with a step-down, would you have to unlock first?

**Comment by chrisesharp** [comment]
No, you'd still be able to drag stuff on, and the consequences would still apply. It would just remove the buttons to roll or step up/down.

**Comment by jwmuk** [comment]
Excellent, I think that works really well for this issue and #9

**Comment by chrisesharp** [comment]
Added to v1.0.7
